name: Main.Yml

on: [push, pull_request, fork]

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout-code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flask pytest

      - name: Test
        run: |
          python -m pytest
          
